export function theme(dark) {
    const c = dark ? {
        bg: "#1f2124",
        bgAlt: "#292b2f",
        bgHover: "#2a2d31",
        border: "#3c3f43",
        text: "#e8eaed",
        textSub: "#9aa0a6",
        textMuted: "#80868b",
        searchBg: "#303134",
        navActive: "#283142",
        composeBg: "#292b2f",
        composeInput: "#292b2f",
        composeField: "#3c3f43",
        mainBg: "#1e2022",
        sidebarBg: "#1f2124",
    } : {
        bg: "#f6f8fc",
        bgAlt: "#fff",
        bgHover: "#f2f6fc",
        border: "#e0e0e0",
        text: "#202124",
        textSub: "#5f6368",
        textMuted: "#5f6368",
        searchBg: "#eaf1fb",
        navActive: "#D3E3FD",
        composeBg: "#fff",
        composeInput: "#fff",
        composeField: "#e0e0e0",
        mainBg: "#fff",
        sidebarBg: "#f6f8fc",
    };

    return {
        root: {
            height: "100vh",
            display: "flex",
            flexDirection: "column",
            background: c.bg,
            fontFamily: "'Google Sans', Roboto, Arial, sans-serif",
            color: c.text,
            overflow: "hidden",
        },
        topbar: {
            height: 64,
            background: c.bg,
            display: "flex",
            alignItems: "center",
            padding: "0 16px 0 8px",
            gap: 16,
            position: "relative",
            zIndex: 10,
        },
        logoArea: {
            display: "flex",
            alignItems: "center",
            gap: 4,
            minWidth: 220,
            paddingLeft: 8,
        },
        hamburger: {
            display: "flex",
            flexDirection: "column",
            gap: 5,
            padding: "8px 12px",
            cursor: "pointer",
            borderRadius: "50%",
            marginRight: 4,
        },
        bar: {
            display: "block",
            width: 18,
            height: 2,
            background: c.textSub,
            borderRadius: 2,
        },
        logoMailPrefix: {
            fontSize: 28,
            fontWeight: 700,
            background: "linear-gradient(90deg, #EA4335, #FBBC05)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            lineHeight: 1,
            letterSpacing: -1,
        },
        logoMail: {
            fontSize: 28,
            fontWeight: 700,
            color: "#EA4335",
            lineHeight: 1,
            letterSpacing: -1,
        },
        logoText: {
            fontSize: 22,
            fontWeight: 400,
            color: c.textSub,
            letterSpacing: -0.5,
            marginTop: 2,
        },
        searchWrap: {
            flex: 1,
            maxWidth: 720,
            display: "flex",
            alignItems: "center",
            gap: 12,
            background: c.searchBg,
            borderRadius: 24,
            padding: "0 20px",
            height: 46,
            color: c.textSub,
            transition: "box-shadow 0.2s",
        },
        searchInput: {
            flex: 1,
            border: "none",
            background: "transparent",
            fontSize: 16,
            color: c.text,
            outline: "none",
            fontFamily: "inherit",
        },
        topRight: {
            marginLeft: "auto",
            position: "relative",
            display: "flex",
            alignItems: "center",
            gap: 10,
        },
        themeToggleBtn: {
            background: "none",
            border: "none",
            cursor: "pointer",
            padding: 0,
            display: "flex",
            alignItems: "center",
        },
        toggleTrack: {
            width: 42,
            height: 24,
            borderRadius: 12,
            background: dark ? "#3c3f43" : "#c8d8f0",
            position: "relative",
            display: "flex",
            alignItems: "center",
            padding: "0 3px",
            transition: "background 0.3s",
            justifyContent: dark ? "flex-end" : "flex-start",
        },
        toggleThumb: {
            width: 18,
            height: 18,
            borderRadius: "50%",
            background: dark ? "#8ab4f8" : "#fff",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
            color: dark ? "#1a73e8" : "#fbbc04",
            transition: "background 0.3s",
            flexShrink: 0,
        },
        userAvatar: {
            display: "flex",
            alignItems: "center",
            gap: 6,
            background: "#EA4335",
            color: "#fff",
            width: 36,
            height: 36,
            borderRadius: "50%",
            fontSize: 15,
            fontWeight: 600,
            cursor: "pointer",
            justifyContent: "center",
            userSelect: "none",
        },
        userMenu: {
            position: "absolute",
            top: 44,
            right: 0,
            width: 280,
            background: c.bgAlt,
            borderRadius: 8,
            boxShadow: dark
                ? "0 4px 24px rgba(0,0,0,0.5)"
                : "0 4px 24px rgba(0,0,0,0.18)",
            overflow: "hidden",
            zIndex: 100,
            border: `1px solid ${c.border}`,
        },
        userMenuHeader: {
            display: "flex",
            alignItems: "center",
            gap: 12,
            padding: "16px 16px 12px",
        },
        userMenuAvatar: {
            width: 40,
            height: 40,
            borderRadius: "50%",
            background: "#EA4335",
            color: "#fff",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontWeight: 700,
            fontSize: 18,
            flexShrink: 0,
        },
        userMenuName: {
            fontWeight: 600,
            fontSize: 14,
            color: c.text,
        },
        userMenuEmail: {
            fontSize: 12,
            color: c.textSub,
            marginTop: 2,
        },
        userMenuDivider: {
            height: 1,
            background: c.border,
            margin: "0 0 4px",
        },
        userMenuBtn: {
            display: "block",
            width: "100%",
            padding: "10px 16px",
            textAlign: "left",
            background: "none",
            border: "none",
            cursor: "pointer",
            fontSize: 14,
            color: c.text,
            fontFamily: "inherit",
            borderRadius: 0,
        },
        body: {
            flex: 1,
            display: "flex",
            overflow: "hidden",
        },
        sidebar: {
            width: 256,
            padding: "8px 0",
            display: "flex",
            flexDirection: "column",
            flexShrink: 0,
            overflowY: "auto",
            background: c.sidebarBg,
        },
        composeBtn: {
            display: "flex",
            alignItems: "center",
            gap: 12,
            margin: "8px 8px 16px 16px",
            padding: "16px 24px 16px 20px",
            background: dark ? "#283142" : "#C2E7FF",
            border: "none",
            borderRadius: 16,
            cursor: "pointer",
            fontSize: 14,
            fontWeight: 500,
            color: dark ? "#8ab4f8" : "#001d35",
            fontFamily: "inherit",
            boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
            transition: "box-shadow 0.2s, background 0.2s",
        },
        nav: {
            display: "flex",
            flexDirection: "column",
            gap: 2,
            padding: "0 8px",
        },
        navItem: {
            display: "flex",
            alignItems: "center",
            gap: 16,
            padding: "8px 16px",
            border: "none",
            background: "transparent",
            cursor: "pointer",
            fontSize: 14,
            color: c.text,
            fontFamily: "inherit",
            fontWeight: 500,
            borderRadius: 24,
            width: "100%",
            textAlign: "left",
            transition: "background 0.15s",
        },
        navItemActive: {
            background: c.navActive,
            fontWeight: 700,
        },
        badge: {
            marginLeft: "auto",
            background: "transparent",
            fontSize: 12,
            fontWeight: 700,
            color: c.text,
        },
        main: {
            flex: 1,
            overflowY: "auto",
            background: c.mainBg,
            borderRadius: 16,
            margin: "0 16px 16px 0",
            border: `1px solid ${c.border}`,
        },
        listArea: {
            display: "flex",
            flexDirection: "column",
        },
        listHeader: {
            padding: "16px 24px 12px",
            borderBottom: `1px solid ${c.border}`,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
        },
        listTitle: {
            fontSize: 14,
            color: c.textSub,
            fontWeight: 500,
        },
        emptyState: {
            padding: 40,
            textAlign: "center",
            color: c.textSub,
            fontSize: 14,
        },
        mailRow: {
            display: "flex",
            alignItems: "flex-start",
            gap: 12,
            padding: "12px 20px",
            borderBottom: `1px solid ${c.border}`,
            cursor: "pointer",
            transition: "background 0.15s",
            background: "transparent",
        },
        mailAvatar: {
            width: 36,
            height: 36,
            borderRadius: "50%",
            background: dark ? "#444" : "#5f6368",
            color: "#fff",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontWeight: 600,
            fontSize: 14,
            flexShrink: 0,
            marginTop: 2,
        },
        mailContent: {
            flex: 1,
            minWidth: 0,
        },
        mailTop: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 2,
        },
        mailFrom: {
            fontWeight: 700,
            fontSize: 14,
            color: c.text,
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
        },
        mailDate: {
            fontSize: 12,
            color: c.textSub,
            flexShrink: 0,
            marginLeft: 8,
        },
        mailSubject: {
            fontSize: 14,
            color: c.text,
            fontWeight: 500,
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
            marginBottom: 2,
        },
        mailSnippet: {
            fontSize: 13,
            color: c.textSub,
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
        },
        detail: {
            padding: "24px 40px",
            maxWidth: 800,
        },
        backBtn: {
            background: "none",
            border: "none",
            color: dark ? "#8ab4f8" : "#1a73e8",
            cursor: "pointer",
            fontSize: 14,
            padding: "0 0 16px",
            fontFamily: "inherit",
            display: "block",
        },
        detailSubject: {
            fontSize: 24,
            fontWeight: 400,
            marginBottom: 20,
            color: c.text,
        },
        metaCard: {
            display: "flex",
            gap: 12,
            marginBottom: 20,
            alignItems: "flex-start",
        },
        metaAvatar: {
            width: 40,
            height: 40,
            borderRadius: "50%",
            background: dark ? "#444" : "#5f6368",
            color: "#fff",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontWeight: 600,
            fontSize: 16,
            flexShrink: 0,
        },
        metaFrom: {
            fontWeight: 600,
            fontSize: 14,
            color: c.text,
        },
        metaDate: {
            fontSize: 12,
            color: c.textSub,
        },
        metaTo: {
            fontSize: 13,
            color: c.textSub,
            marginTop: 2,
        },
        bodyWrap: {
            padding: "20px 0",
            borderTop: `1px solid ${c.border}`,
            marginTop: 8,
        },
        plainText: {
            whiteSpace: "pre-wrap",
            fontSize: 14,
            color: c.text,
            lineHeight: 1.6,
            fontFamily: "inherit",
            margin: 0,
        },
        iframe: {
            width: "100%",
            minHeight: 400,
            border: "none",
        },
        composeWindow: {
            position: "fixed",
            bottom: 0,
            right: 24,
            width: 500,
            background: c.composeBg,
            borderRadius: "12px 12px 0 0",
            boxShadow: dark
                ? "0 8px 40px rgba(0,0,0,0.6)"
                : "0 8px 40px rgba(0,0,0,0.22)",
            zIndex: 1000,
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
        },
        composeMaximized: {
            top: 0, left: 0, right: 0, bottom: 0,
            width: "100%",
            borderRadius: 0,
        },
        composeMinimized: {
            height: 48,
        },
        composeHeader: {
            background: dark ? "#1a1a2e" : "#404040",
            padding: "10px 16px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            cursor: "pointer",
            flexShrink: 0,
        },
        composeTitle: {
            color: "#fff",
            fontWeight: 600,
            fontSize: 14,
        },
        composeActions: {
            display: "flex",
            gap: 4,
        },
        composeIconBtn: {
            background: "none",
            border: "none",
            color: "#fff",
            cursor: "pointer",
            padding: 4,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: 4,
            opacity: 0.8,
        },
        composeFields: {
            borderBottom: `1px solid ${c.border}`,
        },
        composeField: {
            borderBottom: `1px solid ${c.border}`,
        },
        composeInput: {
            width: "100%",
            border: "none",
            padding: "10px 16px",
            fontSize: 14,
            color: c.text,
            background: c.composeBg,
            outline: "none",
            fontFamily: "inherit",
            boxSizing: "border-box",
        },
        composeTextarea: {
            flex: 1,
            width: "100%",
            border: "none",
            padding: "12px 16px",
            fontSize: 14,
            color: c.text,
            background: c.composeBg,
            outline: "none",
            fontFamily: "inherit",
            resize: "none",
            minHeight: 260,
            boxSizing: "border-box",
        },
        composeFooter: {
            display: "flex",
            alignItems: "center",
            gap: 12,
            padding: "12px 16px",
            borderTop: `1px solid ${c.border}`,
            background: c.composeBg,
        },
        sendBtn: {
            background: dark ? "#8ab4f8" : "#0b57d0",
            color: dark ? "#001d35" : "#fff",
            border: "none",
            borderRadius: 20,
            padding: "10px 24px",
            fontSize: 14,
            fontWeight: 600,
            cursor: "pointer",
            fontFamily: "inherit",
        },
        errorMsg: {
            color: "#EA4335",
            fontSize: 13,
            flex: 1,
        },
        successMsg: {
            color: "#34a853",
            fontSize: 13,
            flex: 1,
            fontWeight: 600,
        },
    };
}